### ISSUE TITLE
compile_python uses the wrong root directory

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml-runtime#2]
compile_python.py has the following lines:
```python
    if package_path:
        # We have to calculate the path to expected path relative to the current working directory
        path_from_tests_parent = os.path.relpath(package_path, os.path.join(os.getcwd(), '..'))
        module.__package__ = os.path.dirname(os.path.relpath(path_from_tests_parent, os.getcwd())).replace('/', '.')
```

These lines exist to establish a root path for imports, but `os.getcwd()` gets the working directory from where the python interpreter was invoked, and this isn't always the base path.  You can replicate this issue by running `tox` from the base directory, and note that `module.__package__` = `linkml-runtime.tests.test_issues.input` instead of `tests.test_issues.input`

**Comment by sierra-moxon** [comment]
This code has been updated: https://github.com/linkml/linkml-runtime/blob/6b9f30f0ed5524e05cd9f365d608e890346cb76a/linkml_runtime/utils/compile_python.py#L28 
closing as completed, please of course reopen if I got this wrong.
