### ISSUE TITLE
Unit test for enums fix was updated

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml-runtime#21]
https://github.com/linkml/linkml-runtime/blob/43e9205322696b08014e4153e8ebca52b4cd4834/tests/test_issues/test_issue_368_enums.py#L25 was changed to reflect what we think was intended.  @gaurav - can you check to make sure we got it right.

(Also, we've file an issue to get the PR action to actually RUN the unit tests -- it doesn't at the moment...)

**Comment by gaurav** [comment]
Yup, that's exactly right! Ah, my bad for not noticing the lack of PR tests -- I was unable to run the tests locally (I end up with a `TypeError: don't know how to make test from: <linkml_runtime.dumpers.json_dumper.JSONDumper object at 0x10eef5e50>` if I run `pipenv run python setup.py test`), but was under the incorrect assumption that the PR had run the tests.

**Comment by hsolbrig** [comment]
Mine as well.   Will fix that now...
