### ISSUE TITLE
windows tests are failing

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml-runtime#212]
E.g.
#211

```
 poetry install --no-interaction --no-root
     |  ~~~~~~
     | The term 'poetry' is not recognized as a name of a cmdlet, function, script file, or executable
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct
     | and try again.
```

I see

```
Setting Poetry installation path as /c/Users/runneradmin/.local

Installing Poetry 👷

Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

C:\Users\runneradmin\.local\bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.2.2)
Installing Poetry (1.2.2): Creating environment
Installing Poetry (1.2.2): Installing Poetry
Installing Poetry (1.2.2): Creating script
Installing Poetry (1.2.2): Done

Poetry (1.2.2) is installed now. Great!

To get started you need Poetry's bin directory (C:\Users\runneradmin\.local\bin) in your `PATH`
environment variable.

Alternatively, you can call Poetry explicitly with `C:\Users\runneradmin\.local\bin\poetry`.

You can test that everything is set up by executing:

`poetry --version`
```

is this new? Any idea for the best way to fix this @dalito?

**Comment by dalito** [comment]
This is new and possibly related to a new poetry release. I was using poetry 1.2.0.b3 when I made my last contribution. I need to look in detail.

**Comment by dalito** [comment]
Changes in poetry that broke the github action to install poetry seem to be the problem, see https://github.com/snok/install-poetry/issues/100

In #211 the version `snok/install-poetry@v1.3` was used but newer version are available. Yesterday, 1.3.3 was released. It addresses windows-specifc problems.

Locally I always use pipx to install poetry so I have not hit problems of the poetry-provided installer.

**Comment by dalito** [comment]
An alternative may be to install poetry with pipx and remove the `snok/install-poetry` action.  This is suggested also in the [setup-python action](https://github.com/actions/setup-python/blob/13a464fa1180c0025831475fa35bb1878b1a4728/docs/advanced-usage.md#L234). pipx is availabe by default in the runner-images, see [here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software). A pipx installation is and will continue to be supported by poetry.
