### ISSUE TITLE
Error: unknown url type: 'external_identifiers.yaml' when loading nmdc.yaml from pypi

### ISSUE THREAD

**Issue by wdduncan** [linkml/linkml-runtime#52]
@cmungall  
I am needing/wanting to load SchemaView within `nmdc_runtime`. In the `nmdc-schema` PyPI module, I include the yaml files. So, I can load SchemaView like this:
```python
nmdc_yaml = io.BytesIO(pkgutil.get_data("nmdc_schema", "nmdc.yaml"))
view = SchemaView(nmdc_yaml.getvalue().decode('utf-8'))
```
But when I run an operation like `view.all_class()`, it fails with error:
```python
ValueError: unknown url type: 'external_identifiers.yaml'
```

**Comment by wdduncan** [comment]
Yes. That works!

Should we close the ticket? Or do you want to leave it open for further development?

**Comment by cmungall** [comment]
should we have a convenience method or more docs?

**Comment by wdduncan** [comment]
Perhaps it might be worth adding a flag to the schema view constructor to allow for opening data from a package. E.g.:
```python
SchemaView('nmdc.yaml', module='nmdc_schema')
```
But, this may only be a special case for NMDC.
