### ISSUE TITLE
Bug/UX: `extended_str` incompatibility w/ Neo4j

### ISSUE THREAD

**Issue by joeflack4** [linkml/linkml-runtime#64]
## Description
In the CCDH Terminology Service, we're trying to load a YAML model and import it into Neo4J. Previously we never had this issue when importing the CCDH model into Neo4J. This is new.

## Related issues
https://github.com/py2neo-org/interchange/issues/4
https://github.com/linkml/linkml-runtime/issues/64
https://github.com/cancerDHC/ccdh-terminology-service/issues/115

### Short err
```
TypeError: Values of type <class 'linkml_runtime.utils.yamlutils.extended_str'> are not supported
```

### Long err
```
Traceback (most recent call last):
 File “/usr/local/lib/python3.8/runpy.py”, line 194, in _run_module_as_main
  return _run_code(code, main_globals, None,
 File “/usr/local/lib/python3.8/runpy.py”, line 87, in _run_code
  exec(code, run_globals)
 File “/app/ccdh/importers/importer.py”, line 221, in <module>
  Importer.import_all()
 File “/app/ccdh/importers/importer.py”, line 215, in import_all
  Importer(neo4j_graph()).import_harmonized_attributes(CrdcHImporter.read_harmonized_attributes())
 File “/app/ccdh/importers/importer.py”, line 65, in import_harmonized_attributes
  self.import_harmonized_attribute(harmonized_attribute)
 File “/app/ccdh/importers/importer.py”, line 105, in import_harmonized_attribute
  tx.create(subgraph)
 File “/usr/local/lib/python3.8/site-packages/py2neo/database.py”, line 1063, in create
  create(self)
 File “/usr/local/lib/python3.8/site-packages/py2neo/data.py”, line 200, in __db_create__
  records = tx.run(*pq)
 File “/usr/local/lib/python3.8/site-packages/py2neo/database.py”, line 987, in run
  result = self._connector.run(self.ref, cypher, parameters)
 File “/usr/local/lib/python3.8/site-packages/py2neo/client/__init__.py”, line 1424, in run
  return cx.run(tx, cypher, parameters)
 File “/usr/local/lib/python3.8/site-packages/py2neo/client/bolt.py”, line 571, in run
  return self._run(tx.graph_name, cypher, parameters or {})
 File “/usr/local/lib/python3.8/site-packages/py2neo/client/bolt.py”, line 923, in _run
  response = self.append_message(0x10, cypher, parameters, extra or {})
 File “/usr/local/lib/python3.8/site-packages/py2neo/client/bolt.py”, line 726, in append_message
  self.write_message(tag, fields)
 File “/usr/local/lib/python3.8/site-packages/py2neo/client/bolt.py”, line 701, in write_message
  self._writer.write_message(tag, fields)
 File “/usr/local/lib/python3.8/site-packages/py2neo/client/bolt.py”, line 240, in write_message
  packer.pack(field)
 File “/usr/local/lib/python3.8/site-packages/interchange/packstream.py”, line 151, in pack
  self._pack_dict(value)
 File “/usr/local/lib/python3.8/site-packages/interchange/packstream.py”, line 285, in _pack_dict
  self.pack(item)
 File “/usr/local/lib/python3.8/site-packages/interchange/packstream.py”, line 120, in pack
  self._pack_list(value)
 File “/usr/local/lib/python3.8/site-packages/interchange/packstream.py”, line 247, in _pack_list
  self.pack(item)
 File “/usr/local/lib/python3.8/site-packages/interchange/packstream.py”, line 151, in pack
  self._pack_dict(value)
 File “/usr/local/lib/python3.8/site-packages/interchange/packstream.py”, line 285, in _pack_dict
  self.pack(item)
 File “/usr/local/lib/python3.8/site-packages/interchange/packstream.py”, line 200, in pack
  raise TypeError(“Values of type %s are not supported” % type(value))
TypeError: Values of type <class 'linkml_runtime.utils.yamlutils.extended_str'> are not supported
```

## Possible solutions
(Working through this in: https://github.com/cancerDHC/ccdh-terminology-service/issues/115)

### 1. Have an alternate class to `YAMLRoot`?
This line is what creates the nested object which contains `enhanced_str`:

`model = yaml_loader.loads(yaml, target_class=YAMLRoot)`

Maybe this is a failure of understanding on my part, but there does not appear to be ample documentation / code documentation [for `YAMLLoader`](https://github.com/linkml/linkml-runtime/blob/main/linkml_runtime/loaders/yaml_loader.py#L13).

```python
class YAMLLoader(Loader):

    def load(self, source: Union[str, dict, TextIO], target_class: Type[YAMLRoot], *, base_dir: Optional[str] = None,
             metadata: Optional[FileInfo] = None, **_) -> YAMLRoot:
        def loader(data: Union[str, dict], _: FileInfo) -> Optional[Dict]:
            return yaml.load(StringIO(data), DupCheckYamlLoader) if isinstance(data, str) else data
```

There isn't too much info about `target_class`. But by the looks of it, we could have a subclass of YAMLRoot that uses plain `str` instead of `enhanced_str` perhaps? But I'm not sure what else would have to change. I imagine that `enhanced_str` is there for a reason, and simply converting every instance of it to `str` w/in the object would break something within the object/class.

**Comment by joeflack4** [comment]
@cmungall I haven't figured this out yet; Bill Duncan and I just encountered the issue. However, I wanted you to know that I tried rolling back to previous versions of `linkml` and `linkml_runtime` that were working for us, but I was unable to actually roll back to even the very same versions that are being used on our current deployment at http://terminology.ccdh.io. This is very strange. I'm wondering if previously any PyPi packages have been deleted and the versions re-uploaded with some changes?

I can't think of any other reason why this is happening. I've added more information w/ logs in [the original GitHub issue](https://github.com/cancerDHC/ccdh-terminology-service/issues/115) at the terminology service repo, down at "Possible Solutions > 1. Rollback LinkML versions (temporary)"

**Comment by hsolbrig** [comment]
The source of the problem is that packstream.py doesn't do subtype testing -- it will blow up on _any_ derived type because it uses `type(x) is self.text`.  There is no reason that they should require _only_ strings and integers and the like - derived types should work as well. The correct solution would be `isinstance(x, self.text)` or `issubclass(type(x), self.text)`.

Is there any chance we could convince them to fix their code?  The only other thing I can think of is to add a `__hash__` function to the `TypedNode` metaclass that returns the id of the root class (e.g. `id(str)`) but this is going to break stuff... that said, it won't break nearly as much stuff as changing YAML root or the like.

One other possibility is to use (there may already be one) a function that downcasts `extended_xxx` to the base class.  You could use that going into the neo4j space.

**Comment by cmungall** [comment]
apologies, I only saw this now (I mostly pay attention to issues on the main linkml repo, where I encourage most issues to be filed)

see also discussion here: https://github.com/linkml/linkml/issues/464

**Comment by joeflack4** [comment]
Hey Harold! We just chatted on Skype, but just wanted to reply here. I agree that their code for type detection is not very advanced, and ideally could use more improvement. I think they _might_ have gotten the idea, but they weren't too keen on changing anything. Here's the link to the issue: py2neo-org/interchange#4

**Comment by cmungall** [comment]
Another possibility is to use pydanticgen and to cast objects to pydanticgen (this can be done automatically)

**Comment by cmungall** [comment]
I don't think there is any action here so we can close?

**Comment by joeflack4** [comment]
I think there's room for a UX improvement for this on the linkml end in the event that `interchange` does not make our requested change. But that's unlikely since they already said no and closed the issue. But honestly, it's not really a big deal at this point, so I don't mind closing if you want. Can always be re-opened if another user experiences this same issue.
