### ISSUE TITLE
Post poetry integration steps

### ISSUE THREAD

**Issue by sujaypatil96** [linkml/linkml-runtime#84]
Once PR #80 has been merged into the repo do the following:

- [x] Remove pipenv specific files: Pipfile. requirements.txt and requirements-dev.txt too since they've been generated
- [x] Update Github Actions workflow to use poetry specific specific build steps rather than the current pipenv build steps
- [x] Update Makefile to use poetry build steps

**Comment by dalito** [comment]
This can be closed. The pipenv-related files were removed in #80.
